### ISSUE TITLE
Dependency Error - Legacy Export Bundle 

### ISSUE THREAD

**Issue by rsharma67** [Adobe-Marketing-Cloud/aem-communities-ugc-migration#11]
Hi 

We have a community website which currently stores UGC in JCR  and we are now planning to migrate to MongoDB, We installed Legacy Export bundle to export all the UGC data from JCR, Legacy import bundle is not getting resolved 

**Dependency error** 
com.adobe.cq.social.calendar -- Cannot be resolved
com.adobe.cq.social.journal -- Cannot be resolved
com.adobe.cq.social.storage.buckets,version=[1.0,2) -- Cannot be resolved

I installed **cq-social-storage-1.0.11** in my local AEM to resolve storage dependency error (third one). 

For resolving first 2 errors I download cq-socialcommunities-api-1.4.206 from https://repo.adobe.com/nexus/content/repositories/public/com/adobe/cq/social/cq-socialcommunities-api/1.4.206/ and tried to installed it, the installation failed as the available JAR file do not contain bundle details for MANIFEST.MF like Bundle-SymbolicName, Export-Package, Import-Package, Include-Resource, Service-Component... etc.

Can you please help in resolving the following error,  Which bundle needs to be installed in order resolve the same
com.adobe.cq.social.calendar -- Cannot be resolved
com.adobe.cq.social.journal -- Cannot be resolved

**Comment by vijayyadav06** [comment]
@rsharma67 which AEM version are you using?

I had problems starting bundle on 6.2 earlier but after adding the latest hot fix, service pack and feature pack, the bundle started without trouble. 

I am not sure where our teammember got the following but below are the numbers- 
cq-6.2.0-hotfix-12785-7.0.zip
AEM-6.2-Service-Pack-1-6.2.SP1.zip
AEM-6.2-Communities-Livefyre-Feature-Pack-2-1.10.111.zip

**Comment by rsharma67** [comment]
@vijayyadav06  Sorry I forgot to mention the environment, We are using AEM 6.1 not 6.2 with following packs:  
AEM-6.1-SP2-CFP5-5.0
aem-service-pkg-wrapper-6.1.SP2
cq-6.1.0-hotfix-13455-1.0
cq-6.1.0-sp2-cfp-wrapper-3.0

**Comment by Retesh-Sapient** [comment]
@rsharma67 - Even am facing an dependency error during bundle startup. For your error check if you have Bundle (com.adobe.cq.social.cq-social-ugc-search-collections) in dep finder.

Am using AEM 6.2, my error is below two, even in depfinder I can see related bundle active in my instance but versions are different though, not sure if version are required to be matched. Can anyone point some directions here..

com.adobe.cq.social.scf,version=[1.3,2) -- Cannot be resolved
com.adobe.cq.social.ugc.api,version=[1.4,2) -- Cannot be resolved

AEM Communities SCF Base - API Bundlecom.adobe.cq.social.cq-social-scf-api
AEM Communities UGC SearchCollections - Bundlecom.adobe.cq.social.cq-social-ugc-search-collections

Thanks!

**Comment by Retesh-Sapient** [comment]
My dependency error got solved as soon as I installed AEM-6.2-Communities-Livefyre-Feature-Pack-2-1.10.111.zip. Updating to close the thread i posted.

**Comment by rsharma67** [comment]
Hi Retesh 

This issue is no more valid, after the update in the document 
**package com.adobe.communities.ugc.migration: This provides both an exporter and an importer service for UGC and profile data into and out of AEM 6.1+.**

Thanks 
Ritika Sharma
