### ISSUE TITLE
dependency error in publish instance

### ISSUE THREAD

**Issue by tabassumpatil** [Adobe-Marketing-Cloud/aem-communities-ugc-migration#9]
Hi,

UGC is exported using the LegacyExport in AEM5.6.1
While importing in AEM 6.2 publish instance I am getting dependency error while uploading communities-ugc-migration bundle.

Dependency Error: 
com.adobe.cq.social.scf,version=[1.3,2) -- Cannot be resolved
com.adobe.cq.social.ugc.api,version=[1.4,2) -- Cannot be resolved

Any help is appreciated.

**Comment by mail2nabeel** [comment]
Hi @tabassumpatil , I was able to solve this. 
1. The pom.xml of current project points to uber 6.1 jar. Change the pom.xml to uber 6.2
2. Couple of social dependent jars will throw issues and project will not build. The expected version of jar was not available in adobe repo itself. So I manually changed the expected dependency jar version to available version on repo. Finally your build should get successful after this step
3. Before installing the bundle onto AEM, ensure you have these 3 in this order
- cq-6.2.0-hotfix-12785-7.0.zip
- AEM-6.2-Service-Pack-1-6.2.SP1.zip
- AEM-6.2-Communities-Livefyre-Feature-Pack-2-1.10.111.zip

4.  Restart your AEM and install the migration bundle. It will install without hiccups.
